name: Compile and release EXE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fetching branch
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Prepare Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: make install

      - name: Compile source
        run: make compile

      - name: Release build
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false
          title: Automatic release
          files: dist/*.exe
